nelmio_api_doc:
    documentation:
        info:
            title: Cart and Checkout API
            description: This is a test task for My Mini Factory
            version: 1.0.0
        components:
            securitySchemes:
                ApiToken:
                    type: apiKey
                    in: header
                    name: X-API-TOKEN
        security:
            - ApiToken: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
